Fix typos
progit/progit2-uk pull request #198
Opened 2022-07-30 22:00 UTC by roykoand

2022-07-30 22:14 UTC, roykoand commented
Привіт @hedrok. Не впевнений, що проект ще активний, тим більше в такі складні часи, але знайшов певні моменти для правок. Дякую!

2022-07-31 05:40 UTC, hedrok requested changes
Привіт!

Проєкт не активний, треба зібратися, перечитати нормально, оновити згідно з оновленнями оригіналу, і взагалі купу всього зробити...
Але такі маленькі PR'и я вичитати здатен.
Прокоментував кожну зміну - де "Дякую" чи "Хай буде" - приймаю, решту змін бажано скасувати.

Дякую. за виправлення.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Тепер використаємо `git hash-object`, щоб створити новий обʼєкт даних та вручну зберегти їх у вашій новій базі даних Git:
Це наказовий спосіб, як "ходімо".  Імовірно в оригіналі "Let's", перевіряти ліньки.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Вивід від команди -- 40 символьна хеш-сума.
Дякую.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Концептуально, дані, які зберігає Git, виглядають приблизно так:
Усілякі мовні пуристи вважають, що "виглядати" має лише значення

> визирати; виднітися або ставати видним; чекаючи кого-, що-небудь, дивитися, вдивлятися кудись.

https://goroh.pp.ua/%D0%A1%D0%BB%D0%BE%D0%B2%D0%BE%D0%B2%D0%B6%D0%B8%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F/%D0%B2%D0%B8%D0%B3%D0%BB%D1%8F%D0%B4

А от "скидатися на" ніби цілком нормативно...

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Ви маєте передати опцію `--add`, оскільки файл ще не існує в нашому індексі (у вас навіть немає індексу поки що) та `--cacheinfo`, оскільки файлу, який ви додаєте, не існує у вашій директорії, проте
Дякую.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Інші можливі значення -- `100755`, що означає виконаний файл; та `120000`, що означає символічне посилання.
Ні, ми перекладали executable як "викона́ННИй" - такий, що його можна виконати. "ви́конаний" - це той, що його виконали.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Тепер, ви можете використати  `git write-tree`, щоб записати індекс до об’єкта дерева.
Дякую.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Тепер ви створите нове дерево з другою версією `test.txt`, а також новий файл:
Хай буде.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Зауважте, що це дерево містить обидва файли, а також, що SHA-1 файлу `test.txt` таке саме, як у вищенаведеній ``верcії 2'' цього файлу.
Дякую.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Якщо ви виконали всі вищенаведені команди, то у вас тепер є три дерева, які відповідають різним відбиткам вашого проекту, за якими ви бажаєте слідкувати, проте залишається попередня проблема: ви маєт
Дякую.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Приділимо хвилинку тому, щоб подивитись, як Git зберігає свої обʼєкти.
Знову наказовий спосіб, не бачу причин виправляти.

2022-07-31 05:40 UTC, hedrok commented on book/10-git-internals/sections/objects.asc
> +Git з'єднує заголовок з вмістом, а потім обчислює суму SHA-1 цього нового вмісту.
Хай буде.

2022-07-31 06:11 UTC, roykoand commented
@hedrok Ви праві, дякую! Місцями понадіявся на мовну інтуїцію...

2022-07-31 06:25 UTC, merged