Migrate 02-git-basics/aliases.asc & getting-a-repository.asc
progit/progit2-uk pull request #210
Opened 2024-11-19 08:38 UTC by dev99problems

### Description
This updates some of `02-git-basics` sections to by synced with the latest 2.1.434 version of `eng` original + adds some 
minor adjustments.

2024-11-19 08:40 UTC, dev99problems commented
@hedrok це простіше переглянути коміт за комітом — я спеціально комітив зміни в такий спосіб.

2024-11-20 17:30 UTC, dev99problems commented
@hedrok ping

2024-11-21 07:03 UTC, hedrok requested changes

2024-11-21 07:03 UTC, hedrok commented on book/02-git-basics/sections/getting-a-repository.asc
> +У будь-якому разі ви отримаєте на локальній машині, готове до роботи, Git сховище.
Підкажеш, чому тут коми?..

2024-11-21 07:03 UTC, hedrok commented on book/02-git-basics/sections/getting-a-repository.asc
> +В даний момент у вашому проєкті ще нічого не відстежується.
"В даний момент" ніби неправильно (якщо хочеш, пошукаю джерела). Пропоную взагалі "Поки у вашому...".

2024-11-21 07:03 UTC, hedrok commented on book/02-git-basics/sections/getting-a-repository.asc
> +Ви можете це зробити за допомогою декількох `git add` команд, що визначать файли, які ви плануєте відстежувати і після яких треба виконати `git commit`:
"і після яких" мені спершу читається як "і після файлів", що плутає, та й просто складне речення. Може "відстежувати і після яких треба" -> "відстежувати. Далі треба"?..

2024-11-21 08:19 UTC, dev99problems commented on book/02-git-basics/sections/getting-a-repository.asc
> +У будь-якому разі ви отримаєте на локальній машині, готове до роботи, Git сховище.
Тут зайві, додав випадково, прибираю

2024-11-21 08:19 UTC, dev99problems commented on book/02-git-basics/sections/getting-a-repository.asc
> +В даний момент у вашому проєкті ще нічого не відстежується.
Виправляю

2024-11-21 08:25 UTC, dev99problems commented
Оновив усі місця з зауваженнями

2024-11-21 08:31 UTC, merged

2024-11-21 08:31 UTC, hedrok commented
Дякую, залив.